name: Build CV PDF
on:
  push:
    branches:
      - master  # trigger branch
jobs:
  build_latex:
    runs-on: ubuntu-latext
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cvdanish.tex
